#! /bin/bash

set -e
set -u
set -x

git push -f origin
rsync -avz --exclude='.*.swp' --exclude='siglemic.sqlite' django/ ec2-user@siglemic.net:siglemic.net/django/

ssh -t ec2-user@siglemic.net sudo /etc/init.d/httpd stop
ssh -t ec2-user@siglemic.net 'cd siglemic.net/django && DJANGO_SETTINGS_MODULE=siglemic.settings.production ./manage.py syncdb'
ssh -t ec2-user@siglemic.net sudo /etc/init.d/httpd start
